language: elixir
otp_release:
  - 17.4
notifications:
  email: false
env:
  global:
    secure: dymc5raJD4mRBQ8mQ8+Oz3apifxGR/EVPGFESVZ/E6wwwh9KsxohUSOPq3vEMldIuL83xfmKkss5ZtqWusalGYMuL5cTcxbytGXDO+5/GQaUYTfS6UcTgCThgFOYt0lD1K3d4Y4W3Xmj9/01y5zDnsq8p3rVWNWxhK3xyEMu02w=
cache:
  directories:
    - deps
after_success:
  - git config user.name 'Travis CI'
  - git config user.email 'build@travis-ci.org'
  - git config credential.helper 'store --file=.git/credentials'
  - printf 'https://%s:@github.com' "$GH_TOKEN" > .git/credentials
  - ./scripts/deploy-docs
